### ISSUE TITLE
tune model ?

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/Gurobi.jl#138]
Is it possible to call Gurobi's tune function (https://www.gurobi.com/documentation/8.0/refman/py_model_tune.html) through JuMP? I tried tune_model(m), but Julia did not find it.

**Comment by odow** [comment]
The `Gurobi.tune_model` function accepts a `Gurobi.Model` object:
https://github.com/JuliaOpt/Gurobi.jl/blob/0ba4d2bde9764d382b50db4b8bdf6b8bf6d014a0/src/grb_model.jl#L144-L150

So from JuMP you need to go (nb. I haven't tested this)
```julia
using JuMP, Gurobi
m = Model(solver=GurobiSolver())
# ... add variables etc ...
JuMP.build(m)  # this instantiates the Gurobi model prior to solve
grb = JuMP.internalmodel(m).inner  # get the Gurobi.Model object
Gurobi.tune_model(grb)
solve(m)
```

For future questions like this, a better place is the Discourse forum (https://discourse.julialang.org/c/domain/opt) since many more people read those questions and might be able to help, and it is easier for people to search coming along later :)

**Comment by stumarcus576** [comment]
Will the model m that gets solved by Gurobi via 'solve(m)' use the tuned parameters obtained in the previous step 'Gurobi.tune_model(grb)'? If not, how does one get those tuned parameters and set them in m?

**Comment by odow** [comment]
> Will the Julia code below use the tuned parameters when Gurobi solves the model m?

I should think so. Try it out and let me know if it doesn't.

**Comment by stumarcus576** [comment]
How does one write the tuned model parameters to a .prm file, so that they can be used at a later time without calling tune_model again? My previous post gives the Python code for doing this. In grb_model.jl, I see a function (reproduced below) that may be able to read model parameters in from a .prm file, but not a corresponding Julia function for writing model parameters to a .prm file.
````julia
function read(model::Model, filename::String)
    @assert isascii(filename) # TODO: support non-ascii file names
        ret = @grb_ccall(read, Cint,
        (Ptr{Void}, Ptr{UInt8}),
        model.ptr_model, filename)
    if ret != 0
        throw(GurobiError(model.env, ret))
    end
    nothing
end
````

**Comment by odow** [comment]
Does `write_model` work?

https://github.com/JuliaOpt/Gurobi.jl/blob/0ba4d2bde9764d382b50db4b8bdf6b8bf6d014a0/src/grb_model.jl#L134-L142

**Comment by stumarcus576** [comment]
I will have to try it out. What is the difference between read and read_model? Why isn't there a write in addition to write_model?

**Comment by odow** [comment]
Gurobi provides three functions: https://www.gurobi.com/documentation/8.0/refman/c_input_output.html
- `GRBreadmodel`
- `GRBread`
- `GRBwrite`

These are wrapped as
- https://github.com/JuliaOpt/Gurobi.jl/blob/0ba4d2bde9764d382b50db4b8bdf6b8bf6d014a0/src/grb_model.jl#L120-L124
- https://github.com/JuliaOpt/Gurobi.jl/blob/0ba4d2bde9764d382b50db4b8bdf6b8bf6d014a0/src/grb_model.jl#L109-L111
- https://github.com/JuliaOpt/Gurobi.jl/blob/0ba4d2bde9764d382b50db4b8bdf6b8bf6d014a0/src/grb_model.jl#L134-L136

The `write_model` function is poorly named and should probably have been called `write`.

You should examine the Gurobi documentation to understand what each function does.

**Comment by stumarcus576** [comment]
How does one get Gurobi's tuneResultCount in Julia? In Python: model.tuneResultCount.

**Comment by odow** [comment]
Hi @stumarcus576,

The Julia package `Gurobi.jl` wraps the Gurobi C API.

In the Gurobi documentation, you can find examples for how to query attributes such as "TuneResultCount": http://www.gurobi.com/documentation/8.0/refman/c_attribute_examples.html#CAttributeExamples

Since [TuneResultCount](http://www.gurobi.com/documentation/8.0/refman/tuneresultcount.html) is an integer, we want to use the C function [GRBgetintattr](http://www.gurobi.com/documentation/8.0/refman/c_grbgetintattr.html#routine:GRBgetintattr).

Then, do a search of the Gurobi source for `getintattr` (you can drop the `GRB` prefix).

You will find it here:
https://github.com/JuliaOpt/Gurobi.jl/blob/fb8c3446e9864d3a25d3e5a2caacf581d584ead9/src/grb_attrs.jl#L9-L19

Therefore, you can go
```julia
result_count = Gurobi.getintattr(grb, "TuneResultCount")
```

You can use this process to find all of the functions you wish to use in `Gurobi.jl`. In some cases, the underlying C function may not have been wrapped. In that case, open an issue, or submit a PR :)

Hope that helps,
Oscar

**Comment by odow** [comment]
Closing as there doesn't seem to be an issue with the Gurobi.jl wrapper. Please re-open if that isn't the case, or post on [Discourse](https://discourse.julialang.org/c/domain/opt) if you have future usage questions.
