### ISSUE TITLE
How get dual variables?

### ISSUE THREAD

**Issue by XiaojingGeorgeZhang** [JuliaOpt/Gurobi.jl#164]
Hi all, 
This is not an issue per se, but more of a question. 
Is there a way/command that allows us to extract the dual variables from the solution?
I'd appreciate any pointer :-)
-GXZ

**Comment by odow** [comment]
Hi @XiaojingGeorgeZhang,

If you're using JuMP, please take a look at the [JuMP docs](http://www.juliaopt.org/JuMP.jl/0.18/index.html). The function you're after is `getdual`.

If you're using Gurobi.jl directly (which we don't recommend), you can access standard Gurobi attributes (e.g., `"Pi"`) using functions like 
https://github.com/JuliaOpt/Gurobi.jl/blob/4a872c1ceed82df150558b62d968b09ab12fb18c/src/grb_attrs.jl#L60
(look around the file for the rest).

In the future, please post questions like this to the [Discourse forum](https://discourse.julialang.org/c/domain/opt). As you say, we try to reserve the Github issues for issues rather than questions.

Good luck using Gurobi.jl!

**Comment by odow** [comment]
Closing as this doesn't appear to be an issue with the Gurobi.jl package. Please re-open if that isn't the case.
