### ISSUE TITLE
Trouble with Pkg.add("Gurobi")

### ISSUE THREAD

**Issue by changd** [JuliaOpt/Gurobi.jl#298]
I installed Gurobi 9.0.1 on my Mac and tried Pkg.add("Gurobi") on JuliaPro 1.2.0, but I'm getting the following error message (see copy/pasted material at end of message).

ENV["GUROBI_HOME"] output is 'key "GUROBI_HOME" not found'.

I don't know what the problem was, but Terminal advised that I store the license key file in 'Users/changd' (home directory) rather than 'Library/gurobi' or a similar variant. Also, there is no gurobi-related folder in /Library/ although I successfully installed and tested Gurobi following the Quick Start guide.

How do you advise that troubleshoot?

------------------------------------------

┌ Error: Error building `Gurobi`:
│ dyld: Library not loaded: libgurobi90.dylib
│   Referenced from: /usr/local/bin/gurobi_cl
│   Reason: image not found
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/JuliaOpt/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│
│ Stacktrace:
│  [1] error(::String) at /Applications/JuliaPro-1.2.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [2] top-level scope at /Users/changd/.juliapro/JuliaPro_v1.2.0-1/packages/Gurobi/CI8ht/deps/build.jl:154
│  [3] include_relative(::Module, ::String) at /Applications/JuliaPro-1.2.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [4] include(::Module, ::String) at /Applications/JuliaPro-1.2.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [5] include(::String) at ./client.jl:431
│  [6] top-level scope at none:5
│ in expression starting at /Users/changd/.juliapro/JuliaPro_v1.2.0-1/packages/Gurobi/CI8ht/deps/build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│
│ Gurobi.jl only supports the following versions:
│
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│
│ Did you download and install one of these versions from gurobi.com?
│
│
│ Looking for a version of Gurobi in your path:
│
│
│ We could not find a version of Gurobi in your path, and we could
│ not find the environment variable `GUROBI_HOME`. You should set
│ the `GUROBI_HOME` environment variable to point to the install
│ location. For example:
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/opt/gurobi810/linux64/`
│
│ Alternatively, you can add the Gurobi install directory to your path.

**Comment by dimili** [comment]
I get a similar error but on windows 7 pro. In my case the GUROBI_HOME environment is correct.
I am wondering if the reason is that I have a Julia 1.4.0 32bit while Gurobi 9.0.1 is 64bit.

Error: Error building `Gurobi`:
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/JuliaOpt/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│ 
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\dimili\.julia\packages\Gurobi\CI8ht\deps\build.jl:154
│  [3] include(::String) at .\client.jl:439
│  [4] top-level scope at none:5
│ in expression starting at C:\Users\dimili\.julia\packages\Gurobi\CI8ht\deps\build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│ 
│ Did you download and install one of these versions from gurobi.com?
│ 
│ 
│ Found GUROBI_HOME =  C:\gurobi901\win64
│ 
│ Does this point to the correct install location?
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/home/my_user/gurobi810/linux64/`
│ 
│ Note: this has to be a full path, not a path relative to your current
│ directory or your home directory.
│ 
│ We're going to look for the Gurobi library in this directory:
│     C:\gurobi901\win64\bin
│ 
│ That directory has the following files:
│ 
│  - C:\gurobi901\win64\bin\Gurobi90.NET.XML
│  - C:\gurobi901\win64\bin\Gurobi90.NET.dll
│  - C:\gurobi901\win64\bin\GurobiJni90.dll
│  - C:\gurobi901\win64\bin\grb_ts.exe
│  - C:\gurobi901\win64\bin\grbcluster.exe
│  - C:\gurobi901\win64\bin\grbgetkey.exe
│  - C:\gurobi901\win64\bin\grbprobe.exe
│  - C:\gurobi901\win64\bin\grbtune.exe
│  - C:\gurobi901\win64\bin\gurobi.bat
│  - C:\gurobi901\win64\bin\gurobi.env
│  - C:\gurobi901\win64\bin\gurobi90.dll
│  - C:\gurobi901\win64\bin\gurobi90_light.dll
│  - C:\gurobi901\win64\bin\gurobi_cl.exe
│  - C:\gurobi901\win64\bin\pysetup.bat
│  - C:\gurobi901\win64\bin\vslauncher.exe
│  - C:\gurobi901\win64\bin\vswhere.exe
│ 
│ We were looking for (but could not find) a file named like
│ `libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`. You
│ should update your GUROBI_HOME environment variable to point to the
│ correct location.
└ @ Pkg.Operations D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

**Comment by odow** [comment]
@changd You need to set the `GUROBI_HOME` environment variable to point to wherever you installed Gurobi to. `/Library/gurobi810/mac64` is just an example. It might be `/Applications/Gurobi/mac64` or similar.

@dimili yes, you need matching bit versions of Julia and Gurobi.

**Comment by changd** [comment]
Problem was solved, thanks for the response.
